name: 检出源仓库
description: 检出当前仓库，并将源仓库检出到指定目录

inputs:
  repository:
    description: 源仓库
    required: true
  ref:
    description: 源提交引用
    required: true
  path:
    description: 源仓库检出目录
    required: false
    default: source
  token:
    description: 源仓库访问令牌
    required: true
  fetch-depth:
    description: 检出深度
    required: false
    default: "0"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
